In [1]:
import pandas as pd
import numpy as array 

In [2]:
data=pd.read_excel("stock price lmst.xlsx",sheet_name=0)

In [3]:
data.head()

Date    Open    High     Low    Last   Close  Total Trade Quantity  \
0 2018-09-28  234.05  235.95  230.20  233.50  233.75               3069914   
1 2018-09-27  234.55  236.80  231.10  233.80  233.25               5082859   
2 2018-09-26  240.00  240.00  232.50  235.00  234.25               2240909   
3 2018-09-25  233.30  236.75  232.00  236.25  236.10               2349368   
4 2018-09-24  233.55  239.20  230.75  234.00  233.30               3423509   

   Turnover (Lacs)  
0          7162.35  
1         11859.95  
2          5248.60  
3          5503.90  
4          7999.55

In [4]:
traning_set = data.iloc[:,1:2].values

In [5]:
traning_set

array([[234.05],
       [234.55],
       [240.  ],
       ...,
       [121.8 ],
       [120.3 ],
       [122.1 ]])

In [6]:
type(traning_set)

numpy.ndarray

In [7]:
#scaling 
from sklearn.preprocessing import MinMaxScaler
sc=MinMaxScaler(feature_range=(0,1))

In [8]:
traning_set_scaled = sc.fit_transform(traning_set)
traning_set_scaled

array([[0.6202352 ],
       [0.62226277],
       [0.64436334],
       ...,
       [0.16504461],
       [0.15896188],
       [0.16626115]])

In [9]:
type(traning_set_scaled)

numpy.ndarray

In [15]:
## Example 
dat= traning_set_scaled[0:10]
ls=[]
ls1=[]
for i in range (4,10):
    ls.append(dat[i-4:10])
    ls1.append(dat[i,0])# to reframe it we added 0 

In [16]:
ls

[array([[0.6202352 ],
        [0.62226277],
        [0.64436334],
        [0.61719384],
        [0.61820762],
        [0.62408759],
        [0.62793998],
        [0.63584753],
        [0.61658556],
        [0.57725061]]), array([[0.62226277],
        [0.64436334],
        [0.61719384],
        [0.61820762],
        [0.62408759],
        [0.62793998],
        [0.63584753],
        [0.61658556],
        [0.57725061]]), array([[0.64436334],
        [0.61719384],
        [0.61820762],
        [0.62408759],
        [0.62793998],
        [0.63584753],
        [0.61658556],
        [0.57725061]]), array([[0.61719384],
        [0.61820762],
        [0.62408759],
        [0.62793998],
        [0.63584753],
        [0.61658556],
        [0.57725061]]), array([[0.61820762],
        [0.62408759],
        [0.62793998],
        [0.63584753],
        [0.61658556],
        [0.57725061]]), array([[0.62408759],
        [0.62793998],
        [0.63584753],
        [0.61658556],
        [0.57725061]])]

In [17]:
ls1

[0.6182076236820763,
 0.6240875912408759,
 0.6279399837793997,
 0.6358475263584753,
 0.6165855636658556,
 0.577250608272506]

In [18]:
len(traning_set_scaled)

2035

In [20]:
import numpy as np

In [21]:
#Mian loop input (60)and out put(61 value) 
#similarly doing for the original data as above example 
x_train=[]
y_train=[]

for i in range (60,len(traning_set_scaled)):
    x_train.append(traning_set_scaled[i-60:i,0])
    y_train.append(traning_set_scaled[i,0])#added 0 for formatting
x_train,y_train=np.array(x_train),np.array(y_train)

In [22]:
x_train[0]

array([0.6202352 , 0.62226277, 0.64436334, 0.61719384, 0.61820762,
       0.62408759, 0.62793998, 0.63584753, 0.61658556, 0.57725061,
       0.54845904, 0.57339822, 0.57339822, 0.56731549, 0.57948094,
       0.57137064, 0.63706407, 0.62814274, 0.63219789, 0.62550689,
       0.61942417, 0.63219789, 0.61111111, 0.62206002, 0.64557989,
       0.67234388, 0.66058394, 0.64760746, 0.6283455 , 0.62408759,
       0.61597729, 0.63341444, 0.63077859, 0.63321168, 0.64841849,
       0.62469586, 0.62814274, 0.61394972, 0.67964315, 0.65815085,
       0.6593674 , 0.64841849, 0.62773723, 0.67883212, 0.66058394,
       0.63990268, 0.60888078, 0.6431468 , 0.6784266 , 0.65064882,
       0.71695053, 0.74574209, 0.7676399 , 0.78548256, 0.78994323,
       0.75892133, 0.76520681, 0.79622871, 0.81062449, 0.74371452])

In [24]:
y_train[0:3]

array([0.77007299, 0.73641525, 0.73763179])

In [25]:
x_train.shape[0]

1975

In [26]:
x_train.shape[1]

60

In [28]:
#reshaping
x_train=np.reshape(x_train,(x_train.shape[0],x_train.shape[1],1))

In [29]:
x_train

array([[[0.6202352 ],
        [0.62226277],
        [0.64436334],
        ...,
        [0.79622871],
        [0.81062449],
        [0.74371452]],

       [[0.62226277],
        [0.64436334],
        [0.61719384],
        ...,
        [0.81062449],
        [0.74371452],
        [0.77007299]],

       [[0.64436334],
        [0.61719384],
        [0.61820762],
        ...,
        [0.74371452],
        [0.77007299],
        [0.73641525]],

       ...,

       [[0.19870235],
        [0.21796431],
        [0.21553122],
        ...,
        [0.14963504],
        [0.14801298],
        [0.15815085]],

       [[0.21796431],
        [0.21553122],
        [0.20600162],
        ...,
        [0.14801298],
        [0.15815085],
        [0.16504461]],

       [[0.21553122],
        [0.20600162],
        [0.21654501],
        ...,
        [0.15815085],
        [0.16504461],
        [0.15896188]]])

In [31]:
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import LSTM
from keras.layers import Dropout

In [32]:
model=Sequential()

In [33]:
#First layer
# return_sequenceoutput that we want to be in Sequence or not  
model.add(LSTM(units=50,return_sequences=True,input_shape=(x_train.shape[1],1)))
model.add(Dropout(0.2))


In [34]:
#Secound Layer
model.add(LSTM(units=50,return_sequences=True,))
model.add(Dropout(0.2))

#Third Layer
model.add(LSTM(units=50,return_sequences=True,))
model.add(Dropout(0.2))

In [35]:
model.add(LSTM(units=50))
model.add(Dropout(0.2))

In [36]:
model.add(Dense(units=1))

In [37]:
model.compile(optimizer='adam',loss="mean_squared_error")

In [38]:
model.fit(x_train,y_train,epochs=20,batch_size=32)

Epoch 1/20
1975/1975 [==============================] - 9s 5ms/step - loss: 0.0087
Epoch 2/20
1975/1975 [==============================] - 7s 4ms/step - loss: 0.0030
Epoch 3/20
1975/1975 [==============================] - 8s 4ms/step - loss: 0.0027
Epoch 4/20
1975/1975 [==============================] - 8s 4ms/step - loss: 0.0027
Epoch 5/20
1975/1975 [==============================] - 8s 4ms/step - loss: 0.0025
Epoch 6/20
1975/1975 [==============================] - 8s 4ms/step - loss: 0.0029
Epoch 7/20
1975/1975 [==============================] - 7s 4ms/step - loss: 0.0023
Epoch 8/20
1975/1975 [==============================] - 7s 4ms/step - loss: 0.0020
Epoch 9/20
1975/1975 [==============================] - 7s 4ms/step - loss: 0.0025
Epoch 10/20
1975/1975 [==============================] - 7s 4ms/step - loss: 0.0019
Epoch 11/20
1975/1975 [==============================] - 8s 4ms/step - loss: 0.0019
Epoch 12/20
1975/1975 [==============================] - 8s 4ms/step - loss: 0.0015
E

## Prediction 

In [45]:
#sample example
x_test=x_train[1800:1976]
len(x_train)

1975

In [46]:
x_test

array([[[0.04217356],
        [0.03730738],
        [0.05109489],
        ...,
        [0.06751825],
        [0.0663017 ],
        [0.06650446]],

       [[0.03730738],
        [0.05109489],
        [0.05433901],
        ...,
        [0.0663017 ],
        [0.06650446],
        [0.07055961]],

       [[0.05109489],
        [0.05433901],
        [0.07137064],
        ...,
        [0.06650446],
        [0.07055961],
        [0.06934307]],

       ...,

       [[0.19870235],
        [0.21796431],
        [0.21553122],
        ...,
        [0.14963504],
        [0.14801298],
        [0.15815085]],

       [[0.21796431],
        [0.21553122],
        [0.20600162],
        ...,
        [0.14801298],
        [0.15815085],
        [0.16504461]],

       [[0.21553122],
        [0.20600162],
        [0.21654501],
        ...,
        [0.15815085],
        [0.16504461],
        [0.15896188]]])

In [47]:
np.mean(model.predict(x_test))

0.13904476

In [48]:
s=model.predict(x_test)
s

array([[0.10358191],
       [0.09926096],
       [0.09450546],
       [0.09008539],
       [0.08638455],
       [0.08354542],
       [0.08157868],
       [0.08044294],
       [0.07998149],
       [0.07998185],
       [0.08033907],
       [0.08103025],
       [0.08227301],
       [0.08355264],
       [0.08431775],
       [0.08417117],
       [0.08250309],
       [0.07921779],
       [0.07469667],
       [0.06961054],
       [0.06451783],
       [0.05968698],
       [0.05533523],
       [0.05226293],
       [0.0511281 ],
       [0.05201742],
       [0.05451044],
       [0.0585255 ],
       [0.06329165],
       [0.06795222],
       [0.07182358],
       [0.07427195],
       [0.07470535],
       [0.07296995],
       [0.06982754],
       [0.06648416],
       [0.06403355],
       [0.06294514],
       [0.0632921 ],
       [0.06495442],
       [0.0678125 ],
       [0.07140466],
       [0.07582513],
       [0.08108269],
       [0.08699653],
       [0.09294859],
       [0.0984368 ],
       [0.103

In [49]:
len(s)

175

In [50]:
sc.inverse_transform(s)

array([[106.6433  ],
       [105.57775 ],
       [104.40505 ],
       [103.315056],
       [102.40243 ],
       [101.7023  ],
       [101.2173  ],
       [100.93723 ],
       [100.82343 ],
       [100.823524],
       [100.91161 ],
       [101.08206 ],
       [101.38853 ],
       [101.70408 ],
       [101.89276 ],
       [101.856606],
       [101.44526 ],
       [100.63511 ],
       [ 99.5202  ],
       [ 98.26596 ],
       [ 97.0101  ],
       [ 95.81881 ],
       [ 94.74567 ],
       [ 93.988045],
       [ 93.70819 ],
       [ 93.9275  ],
       [ 94.542274],
       [ 95.532394],
       [ 96.70772 ],
       [ 97.85702 ],
       [ 98.81169 ],
       [ 99.41547 ],
       [ 99.52234 ],
       [ 99.09439 ],
       [ 98.31947 ],
       [ 97.494995],
       [ 96.89067 ],
       [ 96.62227 ],
       [ 96.70783 ],
       [ 97.11776 ],
       [ 97.82256 ],
       [ 98.70839 ],
       [ 99.79848 ],
       [101.09499 ],
       [102.553345],
       [104.021126],
       [105.37452 ],
       [106.5

In [43]:
np.mean(y_train[5:10])

0.7371451743714517